name: Main
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.1.0

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v4.1.0
    with:
      COVERAGE_DISABLE: true

  staging_spuxx_api:
    name: Release artifact (spuxx-api)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
    needs:
    - run_checks
    - run_unit_tests
    with:
      tag: branch
      path: ./apps/spuxx-api
      dockerfile: ./apps/spuxx-api/Dockerfile
      dockerhub_repository: spuxx-api
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  # staging_toledo:
  #   name: Release artifact (toledo)
  #   uses: spuxx1701/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
  #   needs:
  #   - run_checks
  #   - run_unit_tests
  #   with:
  #     tag: branch
  #     dockerfile: ./apps/toledo/Dockerfile
  #     dockerhub_repository: toledo
  #   secrets:
  #     dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  run_release_please:
    name: Run release-please
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_release-please.yml@v4.1.0
    needs:
    - run_checks
    - run_unit_tests
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
