name: Main

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  run_checks:
    name: Run code checks
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_checks.yml@v4.1.0

  run_unit_tests:
    name: Run tests (vitest)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_run_tests_vitest.yml@v4.1.0
    with:
      COVERAGE_DISABLE: true

  staging_spuxx_api:
    name: Release artifact (spuxx-api)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
    needs:
    - run_checks
    - run_unit_tests
    with:
      tag: branch
      path: ./apps/spuxx-api
      dockerfile: ./apps/spuxx-api/Dockerfile
      dockerhub_repository: spuxx-api
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  # staging_toledo:
  #   name: Release artifact (toledo)
  #   uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
  #   with:
  #     tag: branch
  #     path: ./apps/toledo
  #     dockerfile: ./apps/toledo/Dockerfile
  #     dockerhub_repository: toledo
  #   secrets:
  #     dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  release_astro:
    name: Release artifact (spuxx-astro)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_publish_image.yml@v5.0.0
    needs:
    - run_checks
    with:
      tag: branch
      latest: true
      path: ./apps/spuxx-astro
      context: ./apps/spuxx-astro
      # dockerfile: ./apps/spuxx-astro/Dockerfile
      repository: spuxx-astro
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # release_constellation_dashboard:
  #   name: Release artifact (constellation-dashboard)
  #   uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_push_image.yml@v5.0.0
  #   needs:
  #   - run_checks
  #   with:
  #     tag: branch
  #     latest: true
  #     path: ./apps/constellation-dashboard
  #     context: ./apps/constellation-dashboard
  #     dockerfile: ./apps/constellation-dashboard/Dockerfile
  #     dockerhub_repository: constellation-dashboard
  #   secrets:
  #     dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  run_release_please:
    name: Run release-please
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_release-please.yml@v4.1.0
    needs:
    - run_checks
    - run_unit_tests
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
