name: Releases (spuxx-astro)

on:
  workflow_dispatch:
  push:
    tags:
    - "spuxx-astro-*"

jobs:
  release:
    name: Release artifact (spuxx-astro)
    uses: spuxx1701/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
    with:
      path: ./apps/spuxx-astro
      tag: version
      latest: true
      dockerhub_repository: spuxx-astro
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
