name: Releases (spuxx-astro)

on:
  workflow_dispatch:
  push:
    tags:
    - "spuxx-astro-*"

jobs:
  release:
    name: Release artifact (spuxx-astro)
    uses: spuxx-dev/ci-cd/.github/workflows/pnpm_build_and_push.yml@v4.1.0
    with:
      tag: version
      latest: true
      path: ./apps/spuxx-astro
      context: ./apps/spuxx-astro
      dockerfile: ./apps/spuxx-astro/Dockerfile
      dockerhub_repository: spuxx-astro
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
